apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-mks-nov26
  project: giri-may
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: giri-nov26
      operatingSystem: Ubuntu20.04
      privateIP: 10.0.0.6
      roles:
      - Worker
      - ControlPlane
      - Storage
  proxy: {}
  type: mks
