apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx1
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx1/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx1/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: workload-ns
  placement:
    selector: rafay.dev/clusterName=giri-nov27-az
  version: nginx1-v1-202411280216180000
