apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx/nginx-15.4.2.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: nov25
  placement:
    selector: rafay.dev/clusterName=giri-az-nov22
  version: nginx-v1-202411251157140000
