apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx1
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx1/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx1/values.yaml
    type: Helm
  namespace: workload-ns
