apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: xwing
  project: giri-may
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/xwing/xwing.yaml
    type: Yaml
  namespace: addon-ns
  placement:
    selector: rafay.dev/clusterName=giri-nov27-az
  version: xwing-v1-202411280214440000
