apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: manifestsFile
  name: webapp
  project: giri-may
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-oct21-qc1
  resource:
    selector:
      name: web-app
    type: Workload
  type: Yaml
  valuesPath:
    name: file://webapp/webapp.yaml
