apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: req1
  project: giri-may
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
