apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gbp1
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.12.0
  componentsCriticality:
  - name: opa-policy
  - name: network-policy
  - name: cost-profile
  costProfile:
    name: default-cost-profile-azure
    version: version-1732640486
  customAddons:
  - name: xwing1-addon
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator:
        enabled: true
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  networkPolicy:
    profile:
      name: default
      version: latest
  opaPolicy:
    opaPolicy:
    - name: policy-privileged
      version: version-1732640486
    profile:
      name: default
      version: latest
  type: golden
  version: v1
