apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: fad
  name: upst-bp1
  project: giri-may
spec:
  base:
    name: default-upstream
    version: 2.12.0
  customAddons:
  - name: v6
    version: v2
  - name: metallb-config
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    enableRookCeph: true
    monitoring:
      gpuOperator:
        enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
