apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: oct30-ns2
  project: giri-may
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-oct29
    - key: rafay.dev/clusterName
      value: giri-oct30
  resourceQuotas: {}
